# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube
from moviepy.editor import *
import pytube
import os 
import re 
import shutil

def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 200)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoH00")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 70, 141, 41))
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoH00")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("AppleSDGothicNeoH00")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 431, 31))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.mp3ck)
        self.pushButton_2.clicked.connect(MainWindow.mp4ck)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def mp3ck(self):
        pass
    def mp4ck(self):
        textboxValue = self.textEdit.toPlainText()
        pytube.YouTube(textboxValue).streams.filter(only_audio=True).first().download('./BB Download Temp') # 오디오 받기 
        uwu = YouTube(textboxValue).title # 받은 오디오의 확장자를 변환하기 위해 제목을 가져옴 
        uwu = re.sub("[/'*?><|]","", uwu) # 윈도우에서 사용 불가능한 제목 필터링 
        os.rename(f'.\BB Download Temp\{uwu}.mp4',f'.\BB Download Temp\{uwu}.mp3') # 받은 mp4 파일을 mp3로 변환
        pytube.YouTube(textboxValue).streams.filter(res="1080p").first().download('./BB Download Temp') # 영상 다운로드 
        print("encoding..")
        videoclip = VideoFileClip(f'.\BB Download Temp\{uwu}.mp4')
        audioclip = AudioFileClip(f'.\BB Download Temp\{uwu}.mp3')
        videoclip.audio = audioclip
        path = ".\BB Download"
        if not os.path.isdir(path):
            os.mkdir(path)
        videoclip.write_videofile(f'.\BB Download\{uwu}.mp4')
        videoclip.close()
        audioclip.close()
        shutil.rmtree(r".\BB Download Temp")
        print("다운로드 성공")
        #messagebox.showinfo("좋아요!", """다운로드에 성공했어요! 파일은 "./BB Download" 에 넣어둘께요!""") # 창 띄우기 
        #bt["text"] = "슈우웅!"
        #textboxValue = self.textEdit.toPlainText()
        #print(textboxValue)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BB_Downloader"))
        self.label.setText(_translate("MainWindow", "test"))
        self.pushButton.setText(_translate("MainWindow", "PUSH2"))
        self.pushButton_2.setText(_translate("MainWindow", "PUSH1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
